export const PERMISSIONS = {
    UPDATE_ANY_POST: "UPDATE_ANY_POST",
    DELETE_ANY_POST: "DELETE_ANY_POST",
    FORCE_DELETE_ANY_POST: "FORCE_DELETE_ANY_POST",
    RESTORE_ANY_POST: "RESTORE_ANY_POST",
    APPROVE_POST: "APPROVE_POST",

    CREATE_CATEGORY: "CREATE_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",
    FORCE_DELETE_CATEGORY: "FORCE_DELETE_CATEGORY",
    RESTORE_CATEGORY: "RESTORE_CATEGORY",

    APPROVE_COMMENT: "APPROVE_COMMENT",
    DELETE_ANY_COMMENT: "DELETE_ANY_COMMENT",
    RESTORE_ANY_COMMENT: "RESTORE_ANY_COMMENT",

    VIEW_USERS: "VIEW_USERS",
    BAN_USER: "BAN_USER",
    UPDATE_USER_ROLE: "UPDATE_USER_ROLE",

    VIEW_DASHBOARD: "VIEW_DASHBOARD",
} as const;

export type PermissionType = typeof PERMISSIONS[keyof typeof PERMISSIONS];